apiVersion: chaos-mesh.org/v1alpha1
kind: HTTPChaos
metadata:
  name: error-rate-service-c
  namespace: observability
spec:
  mode: all
  selector:
    labelSelectors:
      app: "service-c"
  target: Response     # IMPORTANTE: Cambiado a Response para poder alterar el código de salida
  port: 8080
  duration: '5m'
  replace:
    code: 500          # CORRECCIÓN: Se usa 'code' en lugar de 'statusCode'
